import {
  demeter,
  svpeer,
  gymspike,
  nlwia,
  nlwpython,
  backroads,
} from "../images/index";

export const projects = [
  {
    id: 1,
    img: demeter,
    date: "December 3th, 2023",
    title: "Demeter",
    text: "Project developed for the Computer Science final project at CEUB. Mobile application for inventory management, invoice issuance, and contact for food and agricultural materials commerce.",
    // text: "Projeto realizado para o TCC do curso de Ciência da computação no CEUB. Aplicativo mobile de organização de estoque, emissão de nota fiscal e contato para comercio de alimentos e materiais agrícolas.",
    icon: "fas fa-map",
    href: "https://github.com/TiagoGandra/Demeter",
  },
  {
    id: 2,
    img: svpeer,
    date: "June 19th, 2023",
    title: "Peer-to-peer-IA",
    text: "Project developed for the Distributed Systems Architecture course at CEUB. Virtual peer-to-peer server with one server and two clients integrated with an artificial intelligence for fake news detection.",
    // text: "Projeto realizado para a disciplina de Arquitetura de Sistemas Distribuídos no CEUB. Servidor peer-to-peer virtual, com um servidor e dois clientes integrados a uma inteligência artificial para detecção de fake news.",
    icon: "fas fa-map",
    href: "https://github.com/TiagoGandra/peer-to-peer-IA",
  },
  {
    id: 3,
    img: gymspike,
    date: "January 12th, 2025",
    title: "Gym-Spike",
    text: "Selective project for the Austre team, a web system to help people maintain healthy habits consistently and sustainably through gamification. The project was developed on the front-end with Vite + React + TypeScript + Vanilla CSS and on the back-end with NoSQL (MongoDB Atlas) with Mongoose integration.",
    // text: "Projeto seletivo para a equipe da Austre, onde é um sistema web para ajudar as pessoas a manter hábitos saudáveis de forma consistente e sustentável com gamificação. O projeto foi desenvolvido no front-end com Vite + React + TypeScript + CSS Vanilla e no back-end NoSQL(MongoDB Atlas) com integração via Mongoose.",
    icon: "fas fa-map",
    href: "https://github.com/TiagoGandra/Gym-Spike",
  },
  {
    id: 4,
    img: nlwia,
    date: "July 21th, 2024",
    title: "NLW-IA",
    text: "Generative AI project using GPT LLM models for a travel planner developed during the sixteenth edition of Rocketseat's Next Level Week.",
    // text: "Projeto de uma IA generativa utilizando modelo LLMs GPT para um planner de viagem realizado acompanhando a decima sexta edição do Next Level Week da Rocketseat.",
    icon: "fas fa-map",
    href: "https://github.com/TiagoGandra/NLW-IA",
  },
  {
    id: 5,
    img: nlwpython,
    date: "July 21th, 2024",
    title: "NLW-Python",
    text: "Back-End project of a travel planner database developed during the sixteenth edition of Rocketseat's Next Level Week.",
    // text: "Projeto Back-End um banco de dados de um planner de viagem realizado acompanhando a decima sexta edição do Next Level Week da Rocketseat.",
    icon: "fas fa-map",
    href: "https://github.com/TiagoGandra/NLW-Python",
  },
  {
    id: 6,
    img: backroads,
    date: "March 23th, 2025",
    title: "Backroads",
    text: "Landing Page for a tourism service. Vite was used to create the React project with JavaScript and Vanilla CSS.",
    // text: "Landing Page de um serviço de turismo. Foi utilizado Vite para a criação do projeto React com JavaScript e CSS Vanilla.",
    icon: "fas fa-map",
    href: "https://github.com/TiagoGandra/backroads",
  },
];